CREATE TABLE `chat_messages` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `session_id` bigint NOT NULL COMMENT '→ chat_sessions.id',
  `role` varchar(16) NOT NULL COMMENT 'user / assistant / system',
  `content` text NOT NULL COMMENT '消息文本',
  `status` varchar(16) NOT NULL COMMENT 'pending / streaming / done / error / partial / aborted',
  `parent_id` bigint DEFAULT NULL COMMENT '→ chat_messages.id',
  `tool_calls` json DEFAULT NULL COMMENT '工具调用记录',
  `citations` json DEFAULT NULL COMMENT '引用列表',
  `usage` json DEFAULT NULL COMMENT 'token 用量',
  `error_message` text COMMENT '错误信息',
  `reasoning_content` text COMMENT '思考链文本',
  `reasoning_duration_ms` int DEFAULT NULL COMMENT '思考耗时 ms',
  `context_meta` json DEFAULT NULL COMMENT '上下文元信息',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_cm_session` (`session_id`),
  KEY `ix_cm_parent` (`parent_id`),
  KEY `ix_cm_role_status` (`role`,`status`),
  KEY `ix_cm_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='聊天消息表';

CREATE TABLE `chat_sessions` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `user_id` bigint NOT NULL COMMENT '→ users.id (雪花, 应用层引用, 无 FK)',
  `title` varchar(255) NOT NULL COMMENT '会话标题',
  `workspace_id` varchar(255) NOT NULL COMMENT 'workspace 路径',
  `status` varchar(16) NOT NULL COMMENT 'active / deleted',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_cs_status` (`status`),
  KEY `ix_cs_updated` (`updated_at`),
  KEY `ix_cs_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='聊天会话表';

CREATE TABLE `kb_documents` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `kb_id` bigint NOT NULL COMMENT '→ knowledge_bases.id (应用层引用, 无 FK)',
  `name` varchar(512) NOT NULL COMMENT '显示文件名',
  `source` varchar(16) NOT NULL COMMENT 'upload / url / api',
  `source_url` varchar(2048) DEFAULT NULL COMMENT '原始 URL',
  `storage_path` varchar(1024) DEFAULT NULL COMMENT '文件存储路径',
  `mime_type` varchar(128) NOT NULL COMMENT 'MIME 类型',
  `size_bytes` bigint NOT NULL COMMENT '文件字节大小',
  `content_hash` varchar(128) DEFAULT NULL COMMENT 'SHA256 去重',
  `status` varchar(16) NOT NULL COMMENT 'pending / parsing / chunking / embedding / indexed / failed',
  `status_message` text COMMENT '状态详情',
  `progress` int NOT NULL COMMENT '进度 0-100',
  `chunk_count` int NOT NULL COMMENT '切分后的分块数',
  `indexed_at` datetime DEFAULT NULL COMMENT '完成索引时间',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_kb_docs_status` (`kb_id`,`status`),
  KEY `ix_kb_docs_hash` (`content_hash`),
  KEY `ix_kb_docs_kb_created` (`kb_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='知识库文档表 (用户上传)';
CREATE TABLE `knowledge_bases` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `name` varchar(128) NOT NULL COMMENT '知识库名称',
  `description` text COMMENT '描述',
  `visibility` varchar(16) NOT NULL COMMENT 'private / workspace / public',
  `owner_id` bigint NOT NULL COMMENT '→ users.id (应用层引用, 无 FK)',
  `collaborators` json DEFAULT NULL COMMENT '协作者列表',
  `embedding_model` varchar(128) NOT NULL COMMENT 'embedding 模型标识',
  `chunk_size` int NOT NULL COMMENT '分块字符数',
  `chunk_overlap` int NOT NULL COMMENT '分块重叠字符数',
  `document_count` int NOT NULL COMMENT '文档总数',
  `chunk_count` int NOT NULL COMMENT '分块总数',
  `size_bytes` bigint NOT NULL COMMENT '文件总字节数',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_kb_visibility` (`visibility`),
  KEY `ix_kb_owner` (`owner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='知识库 (KB) 元数据表';
CREATE TABLE `message_digests` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `message_id` bigint NOT NULL COMMENT '→ chat_messages.id (雪花)',
  `session_id` bigint DEFAULT NULL COMMENT '→ chat_sessions.id (雪花)',
  `segments` json NOT NULL COMMENT '分段列表 [{kind,start_line,end_line,anchor,digest_text}]',
  `total_tokens` int NOT NULL COMMENT '原文 token 估算',
  `source_hash` varchar(64) NOT NULL COMMENT '原文内容 hash, 判 stale',
  `model` varchar(128) DEFAULT NULL COMMENT '生成 prose 摘要所用模型 (代码骨架为空)',
  `status` varchar(16) NOT NULL COMMENT 'pending / done / failed',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `message_id` (`message_id`),
  KEY `ix_message_digests_session_id` (`session_id`),
  KEY `ix_digest_updated` (`updated_at`),
  KEY `ix_digest_session` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='消息 digest 缓存表 (一 message 一条, 按 message_id 原地 upsert)';

CREATE TABLE `models` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `provider_id` bigint NOT NULL COMMENT '→ providers.id',
  `name` varchar(128) NOT NULL COMMENT '模型名: gpt-4o / qwen-plus / text-embedding-v3',
  `display_name` varchar(128) NOT NULL COMMENT '展示名',
  `model_type` varchar(32) NOT NULL COMMENT 'text / embedding / reranker / image / audio',
  `context_window` int NOT NULL COMMENT '上下文窗口长度',
  `max_output_tokens` int NOT NULL COMMENT '最大输出 token',
  `supports_tools` tinyint(1) NOT NULL COMMENT '是否支持工具调用',
  `supports_images` tinyint(1) NOT NULL COMMENT '是否支持图片识别',
  `supports_thinking` tinyint(1) NOT NULL COMMENT '是否支持思考模式',
  `thinking_options` json DEFAULT NULL COMMENT '思考强度档位: ["standard","low","medium","high","xhigh"]',
  `extra_params` json DEFAULT NULL COMMENT '类型特定参数: dimension / batch_size / timeout / truncation ...',
  `cost_tier` varchar(16) NOT NULL COMMENT 'cheap / mid / expensive',
  `is_enabled` tinyint(1) NOT NULL COMMENT '启用标识',
  `is_default` tinyint(1) NOT NULL COMMENT '是否该供应商的默认模型',
  `priority` int NOT NULL COMMENT '同类型内优先级',
  `is_stale` tinyint(1) NOT NULL COMMENT 'API 不再返回时标记',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_models_biz_key` (`provider_id`,`model_type`,`name`),
  KEY `ix_models_type_enabled` (`model_type`,`is_enabled`),
  KEY `ix_models_type` (`model_type`),
  KEY `ix_models_enabled` (`is_enabled`),
  KEY `ix_models_provider` (`provider_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='模型信息表';

CREATE TABLE `provider_keys` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `provider_id` bigint NOT NULL COMMENT '→ providers.id',
  `key_ciphertext` text NOT NULL COMMENT 'API Key (AES-256-GCM 加密)',
  `key_fingerprint` varchar(12) NOT NULL COMMENT 'Key 指纹, 日志脱敏',
  `is_enabled` int NOT NULL,
  `weight` int NOT NULL COMMENT '负载权重',
  `cooldown_until` datetime DEFAULT NULL COMMENT '429 冷却到何时',
  `failure_score` int NOT NULL,
  `last_error_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_pk_provider` (`provider_id`),
  KEY `ix_pk_enabled` (`is_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商 API Key 表';
CREATE TABLE `providers` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `name` varchar(64) NOT NULL COMMENT 'anthropic / openai / deepseek / dashscope',
  `impl` varchar(64) DEFAULT NULL COMMENT 'SDK 实现类名',
  `base_url` varchar(512) DEFAULT NULL COMMENT 'API 地址, NULL=官方默认',
  `is_enabled` int NOT NULL,
  `priority` int NOT NULL,
  `routing_config` json DEFAULT NULL COMMENT 'fallback 图谱 / 重试策略',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `ix_prov_enabled` (`is_enabled`),
  KEY `ix_prov_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LLM 供应商表';
CREATE TABLE `refresh_token_blacklist` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `jti` varchar(64) NOT NULL COMMENT 'JWT ID, refresh token 唯一标识',
  `user_id` bigint NOT NULL COMMENT '→ users.id (应用层引用, 无 FK)',
  `expires_at` datetime NOT NULL COMMENT '原 token 过期时间, 用于定期清理',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `jti` (`jti`),
  KEY `ix_blacklist_user` (`user_id`),
  KEY `ix_blacklist_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='已撤销的 refresh token 黑名单';
CREATE TABLE `session_summaries` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `session_id` bigint NOT NULL COMMENT '→ chat_sessions.id (雪花)',
  `workspace_id` varchar(255) DEFAULT NULL COMMENT '工作空间 ID',
  `content` text NOT NULL COMMENT '摘要正文',
  `covered_until_message_id` bigint DEFAULT NULL COMMENT '摘要覆盖到哪条消息为止 (→ chat_messages.id 雪花)',
  `token_count` int NOT NULL COMMENT '摘要 token 估算',
  `version` int NOT NULL COMMENT '版本号',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `session_id` (`session_id`),
  KEY `ix_session_summaries_workspace_id` (`workspace_id`),
  KEY `ix_summary_updated` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会话摘要表 (一 session 一条, 原地 upsert)';
CREATE TABLE `user_api_keys` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `user_id` bigint NOT NULL COMMENT '→ users.id (应用层引用, 无 FK)',
  `name` varchar(128) NOT NULL COMMENT 'Key 名称（用户自定义标签）',
  `key_hash` varchar(64) NOT NULL COMMENT 'API Key 的 SHA256 哈希',
  `prefix` varchar(12) NOT NULL COMMENT 'Key 前缀，用于 UI 回显辨识（如 fk_a1b2c3d4）',
  `last_used_at` datetime DEFAULT NULL COMMENT '最后一次使用时间',
  `expires_at` datetime DEFAULT NULL COMMENT '过期时间，NULL 表示永不过期',
  `is_revoked` tinyint(1) NOT NULL COMMENT '是否已吊销',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `key_hash` (`key_hash`),
  KEY `ix_api_key_hash` (`key_hash`),
  KEY `ix_api_key_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户 API Key 表';

CREATE TABLE `users` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Snowflake 主键',
  `email` varchar(255) NOT NULL COMMENT '登录邮箱, 唯一',
  `name` varchar(64) NOT NULL COMMENT '显示名称',
  `avatar_url` varchar(512) DEFAULT NULL COMMENT '头像 URL',
  `role` varchar(16) NOT NULL COMMENT '角色: owner / admin / member / guest',
  `status` varchar(16) NOT NULL COMMENT '状态: active / disabled / pending',
  `password_hash` text NOT NULL COMMENT 'bcrypt 哈希后的密码',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `ix_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户账号表';